---
title: "Publications"
editor: visual
format: 
  html:
    css: custom.css 
---

```{=html}
<style>
    /* Smooth transition */
    .btn-outline-success {
        transition: all 0.3s ease;
    }

    /* Change on hover */
    .btn-outline-success:hover {
        border-color: #76A5AF;
        background-color: #76A5AF;
        color: white;
    }

    /* Optional: Active state when clicked */
    .btn-outline-success:active {
        border-color: #507f89;
        background-color: #507f89;
        color: white;
    }
</style>

    <style>
        /* Custom class for extra-small button */
        .btn-xs {
            padding: 0.15rem 0.3rem;  /* Smaller padding */
            font-size: 0.6rem;        /* Smaller font size */
            line-height: 1.1;         /* Adjust line height to match the new size */
        }
    </style>
```
[**Work in Preparation**]{.underline}

~For more details about ongoing work, see [research](research.qmd).~

**Langer, A.,** Martinez, S., Marshall, J. P., Chein, J. (under review). Children’s Susceptibility to Content Generated by Artificial Intelligence.

**Langer, A.,** Wilson, J. R., Howard, L., & Marshall, P. J. (under review). The Influence of Child Characteristics on Children’s Behavior towards a Social Robot Versus a Human.

**Langer, A.** (in preparation). Scoping Review of Evidence from EEG for Altered Brain Responses among Technology Users from Infancy to Young Adulthood.

[**Child-Robot Interactions (CRI)**]{.underline}

**Langer, A.,** Marshall, P. J., & Levy-Tzedek, S. (2023). Ethical Considerations in Child-Robot Interactions. *Neuroscience & Biobehavioral Reviews*, 105230. \|  <a href="https://www.sciencedirect.com/science/article/pii/S0149763423001999#:~:text=Sharkey%20and%20Sharkey%20(2020)%20argue,of%20interactions%20with%20human%20beings." style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>

Yang, Y., **Langer, A.,** Howard, L., Marshall, P. J., & Wilson, J. R. (2023). Towards an Ontology for Generating Behaviors for Socially Assistive Robots Helping Young Children. *Proceedings of the Association of Advancement of Artificial Intelligence* (Vol. 2, No. 1, pp. 213-218). \|  <a href="https://ojs.aaai.org/index.php/AAAI-SS/article/view/27674" style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>

[**Human Robot Interaction (HRI)**]{.underline}

**Langer, A.**, Levy-Tzedek, S. (2021). Emerging Roles for Social Robots in Rehabilitation: Current Directions. *ACM Transactions on Human-Robot Interaction (THRI)*, Volume 10, Issue 4 \|  <a href="https://dl.acm.org/doi/10.1145/3462256" style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>

**Langer, A.**, Levy-Tzedek S. (2020). Priming and Timing in Human-Robot Interactions. In: Noceti N., Sciutti A., Rea F. (eds) *Modelling Human Motion: From Human Perception to Robot Design*. Springer, Cham. \|  <a href="https://link.springer.com/chapter/10.1007/978-3-030-46732-6_16" style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>

**Langer, A.**, Feingold-Polak R., Mueller O., Kellmeyer P., Levy-Tzedek S. (2019). Trust in Socially Assistive Robots: Considerations for use in Neurological Rehabilitation. *Neuroscience & Biobehavioral Reviews*, 104, 231-239. \| <a href="https://www.sciencedirect.com/science/article/pii/S014976341930199X?via%3Dihub" style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>

[**Autism Spectrum Conditions**]{.underline}

Taylor, S. C., Gehringer, B. N., Dow, H. C., **Langer, A.**, Rawot, E., Smernoff, Z., Steeman, S., Almasy, L., Rader, D. J., Bučan, M., & Brodkin, E. S. (2022). Contrasting Views of Autism Spectrum Traits in Adults, Especially in Self-Reports vs. Informant-Reports for Women High in Autism Spectrum Traits. *Journal of Autism and Developmental Disorders*, 1–13. \| <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9734875/" style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>

Elkhatib Smidt, S. D., Ghorai, A., Taylor, S. C., Gehringer, B. N., Dow, H. C., **Langer, A.**, Rawot, E., Zhang, J., Mitchell, J. A., Rader, D. J., Almasy, L., Brodkin, E. S., & Bućan, M. (2022). The relationship between autism spectrum and sleep–wake traits. *Autism Research*, 15(4), 641-652. \| <a href="https://onlinelibrary.wiley.com/doi/10.1002/aur.2660" style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>

Taylor, S. C., Steeman, S., Gehringer, B. N., Dow, H. C., **Langer, A.**, Rawot, E., Perez, L., Goodman, M., Smernoff, Z., Grewal, M., Eshraghi, O., Pallathra, A. A., Oksas, C., Mendez, M., Gur, R. C., Rader, D. J., Bucan, M., Almasy, L., & Brodkin, E. S. (2021). Heritability of quantitative autism spectrum traits in adults: A family-based study. *Autism Research*, 14(8), 1543-1553. \| <a href="https://onlinelibrary.wiley.com/doi/abs/10.1002/aur.2571" style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>

Budman I., Meiri G., Ilan M., Faroy M., **Langer, A**., Reboh D., Michaelovski A., Flusser H., Menashe I., Donchin O., Dinstein I. (2019). Quantifying the social symptoms of autism using motion capture. *Scientific Reports*, 2019, 9: 7712. \| <a href="https://www.nature.com/articles/s41598-019-44180-9" style="text-decoration:none" class="btn btn-info btn-xs">Link</a> <br>
